import React from 'react'

import Navbar from '../components/home/navbar'
import Head from 'next/head'
import Footer from '../components/home/footer'
import Contactku from '../components/contact/contactku'
import { motion } from 'framer-motion'
import Animasi from '../components/animasi'




export default function About() {
    return (
        <>
        <Animasi/>
      <motion.div 
       initial={{ visibility: "hidden" }}
       exit={{
         visibility: "hidden",
         transition: { delay: 1 },
       }}
       animate={{
         visibility: "visible",
         transition: { delay: 1 },
       }}
      >
        <Head>
          <title>Contact-Anggabimantoro</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <Contactku/>
      <Footer/>
      </motion.div>
      </>
    )
  }
  